name: Build and deploy basketball league

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy basketball league
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build and tag Docker image using Maven
        run: |
          mvn clean install -DskipTests
          docker tag basketball-league:latest ${{ secrets.DOCKER_HUB_USERNAME }}/basketball_league:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/basketball_league:latest




